import type { Metadata } from "next";

import { TbCards, TbChartBar, TbDatabase, TbSwords } from "react-icons/tb";

// These styles apply to every route in the application
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <div className="flex flex-row">
          <nav className="flex flex-col p-4">
            <div className="w-36 h-16"></div>
            <div className="divider" />
            <ul className="menu menu-sm lg:menu-md py-0">
              <li>
                <a href="/">
                  <TbChartBar />
                  Home
                </a>
              </li>
              <li>
                <a href="/play">
                  <TbSwords />
                  Play
                </a>
              </li>
              <li>
                <a href="/deck">
                  <TbCards />
                  Deck
                </a>
              </li>
              <li>
                <a href="/cards">
                  <TbDatabase />
                  Cards
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
